In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('myExcelFile.xlsx',sheet_name='my_data') #Wprowadzenie parametru określającego nazwę zakładki, z której Pandas postara się pobrać dane, jest opcjonalne. Domyślnie wczytana będzie zawartość pierwszej zakładki.

In [5]:
df.to_excel('myNewExcelFile.xlsx', sheet_name='my_new_data')

In [6]:
df.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [7]:
df.tail()

     A    B    C
6    6   36  300
7    7   49  350
8    8   64  400
9    9   81  450
10  10  100  500

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       11 non-null     int64
 1   B       11 non-null     int64
 2   C       11 non-null     int64
dtypes: int64(3)
memory usage: 396.0 bytes

df.describe()

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [10]:
writer = pd.ExcelWriter('pandas_simple.xlsx', engine='xlsxwriter')

In [11]:
df.to_excel(writer, sheet_name='my_dfs')
df.to_excel(writer, sheet_name='my_dfs', startcol=6, startrow=5, index=False)

In [12]:
df.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [13]:
import pandas as pd

with pd.ExcelWriter('many_sheets.xlsx', engine='xlsxwriter') as writer:
    
    df.to_excel(writer, sheet_name='my_df1', index=False)
    df.to_excel(writer, sheet_name='my_df2', index=False)

In [14]:
df.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [15]:
df1 = pd.read_excel('many_sheets.xlsx', sheet_name='my_df1')

In [16]:

df2 = pd.read_excel('many_sheets.xlsx', sheet_name='my_df2')

In [17]:
df1.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [18]:
df2.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [19]:
xls = pd.ExcelFile('many_sheets.xlsx')
xls.sheet_names

['my_df1', 'my_df2']

In [20]:
all_sheets = pd.read_excel('many_sheets.xlsx', sheet_name=None)

In [21]:
all_sheets['my_df1']
all_sheets['my_df2']

     A    B    C
0    0    0    0
1    1    1   50
2    2    4  100
3    3    9  150
4    4   16  200
5    5   25  250
6    6   36  300
7    7   49  350
8    8   64  400
9    9   81  450
10  10  100  500

In [22]:
df1 = pd.read_excel('many_sheets.xlsx', sheet_name='my_df1')
df1.head(12)

     A    B    C
0    0    0    0
1    1    1   50
2    2    4  100
3    3    9  150
4    4   16  200
5    5   25  250
6    6   36  300
7    7   49  350
8    8   64  400
9    9   81  450
10  10  100  500

In [23]:
writer = pd.ExcelWriter('add_chart.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='my_chart')

In [24]:
workbook = writer.book
worksheet = writer.sheets['my_chart']

In [25]:
chart = workbook.add_chart({'type':'line'})

In [26]:
def grab_series(df, sheet_name, colname, startcol=0, startrow=0):

    col_index = df.columns.tolist().index(colname)
    col_letter = chr(ord('@')+(col_index+2+startcol))
    first_row = startrow + 2
    last_row = startrow + 1 + len(df)
    return f"='{sheet_name}'!{col_letter}{first_row}:{col_letter}{last_row}"

In [27]:
chart.add_series({'values':grab_series(df,'my_chart','B')})

In [28]:
chart.set_x_axis({
    'name': 'x^2',
    'name_font': {'size': 14, 'bold': True},
    'num_font':  {'italic': True },
})

In [29]:
chart.set_legend({'none': True})

In [30]:
worksheet.insert_chart('F2', chart)

0

In [31]:
workbook.close()

TABELE HTML

In [32]:
url = "https://pl.wikipedia.org/wiki/Miasta_w_Polsce"

tables = pd.read_html(
    url,
    header=0,
    storage_options={
        "User-Agent": "Mozilla/5.0"
    }
)

In [33]:
len(tables)

5

In [34]:
tables[0] # pierwsza tabela

,Lp.,Miasto,Województwo,Liczba mieszkańców,Gęstość zaludnienia [osoby/km²]
0,1.0,Warszawa,mazowieckie,1 862 402,3601
1,2.0,Kraków,małopolskie,807 644,2471
2,3.0,Wrocław,dolnośląskie,673 531,2300
3,4.0,Łódź,łódzkie,648 711,2212
4,5.0,Poznań,wielkopolskie,536 818,2050
5,6.0,Gdańsk,pomorskie,487 834,714
6,7.0,Szczecin,zachodniopomorskie,387 700,1290
7,8.0,Lublin,lubelskie,328 868,2230
8,9.0,Bydgoszcz,kujawsko-pomorskie,324 984,1847
9,10.0,Białystok,podlaskie,290 907,2848

In [35]:
tables[1]

    Lp.        Miasto         Województwo Powierzchnia [ha]
0   1.0        Gdańsk           pomorskie            68 300
1   2.0      Warszawa         mazowieckie            51 720
2   3.0        Gdynia           pomorskie            39 151
3   4.0        Kraków         małopolskie            32 685
4   5.0      Szczecin  zachodniopomorskie            30 062
5   6.0          Łódź             łódzkie            29 325
6   7.0       Wrocław        dolnośląskie            29 280
7   8.0  Zielona Góra            lubuskie            27 536
8   9.0        Poznań       wielkopolskie            26 191
9  10.0   Świnoujście  zachodniopomorskie            20 207

# ZADANIE

In [36]:
url = "https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/"

tables = pd.read_html(
    url,
    header=0,
    storage_options={
        "User-Agent": "Mozilla/5.0"
    }
)

In [37]:
len(tables)

1

In [38]:
df = tables[0]

zmiana nazw wybranych kolumn

In [39]:
df = df.rename(columns={
    'TITLE' : 'TYTUŁ',
    'ARTIST' : 'ARTYSTA',
    'YEAR' : 'ROK',
    'HIGH POSN' : 'MAX POZ'
})

In [40]:
df.columns = df.columns.str.strip() #czyszczenie nazw- usuniecie spacji

In [41]:
df.head() # z defaultu zawsze 5 wierszy

   POS                                 TYTUŁ  ARTYSTA   ROK  MAX POZ
0    1                         GREATEST HITS    QUEEN  1981        1
1    2                  GOLD - GREATEST HITS     ABBA  1992        1
2    3  SGT PEPPER'S LONELY HEARTS CLUB BAND  BEATLES  1967        1
3    4                                    21    ADELE  2011        1
4    5        WHAT'S THE STORY MORNING GLORY    OASIS  1995        1

In [42]:
df['ARTYSTA'].nunique() #liczba unikalnych artystow

47

In [43]:
df['ARTYSTA'].value_counts().head() #ile razy pojawia sie dany artysta

ARTYSTA
COLDPLAY     3
TAKE THAT    3
QUEEN        2
ABBA         2
BEATLES      2
Name: count, dtype: int64

In [44]:
df.columns = df.columns.str.capitalize()  #headry z duzych liter a reszta malymi

In [45]:
df

,Pos,Tytuł,Artysta,Rok,Max poz
0,1,GREATEST HITS,QUEEN,1981,1
1,2,GOLD - GREATEST HITS,ABBA,1992,1
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967,1
3,4,21,ADELE,2011,1
4,5,WHAT'S THE STORY MORNING GLORY,OASIS,1995,1
5,6,THRILLER,MICHAEL JACKSON,1982,1
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973,2
7,8,BROTHERS IN ARMS,DIRE STRAITS,1985,1
8,9,BAD,MICHAEL JACKSON,1987,1
9,10,GREATEST HITS II,QUEEN,1991,1
10,11,RUMOURS,FLEETWOOD MAC,1977,1
11,12,THE IMMACULATE COLLECTION,MADONNA,1990,1
12,13,BACK TO BLACK,AMY WINEHOUSE,2006,1
13,14,STARS,SIMPLY RED,1991,1
14,15,COME ON OVER,SHANIA TWAIN,1997,1
15,16,LEGEND,BOB MARLEY & THE WAILERS,1984,1
16,17,BACK TO BEDLAM,JAMES BLUNT,2004,1
17,18,URBAN HYMNS,VERVE,1997,1
18,19,BAT OUT OF HELL,MEAT LOAF,1977,9
19,20,1,BEATLES,2000,1
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970,1
21,22,DIRTY DANCING,ORIGINAL SOUNDTRACK,1987,4
22,23,SPIRIT,LEONA LEWIS,2007,1
23,24,CRAZY LOVE,MICHAEL BUBLE,2009,1
24,25,NO ANGEL,DIDO,2000,1
25,26,WHITE LADDER,DAVID GRAY,1998,1
26,27,25,ADELE,2015,1
27,28,TALK ON CORNERS,CORRS,1997,1
28,29,SPICE,SPICE GIRLS,1996,1
29,30,THE FAME,LADY GAGA,2008,1
30,31,A RUSH OF BLOOD TO THE HEAD,COLDPLAY,2002,1
31,32,LIFE FOR RENT,DIDO,2003,1
32,33,ONLY BY THE NIGHT,KINGS OF LEON,2008,1
33,34,BEAUTIFUL WORLD,TAKE THAT,2006,1
34,35,HOPES AND FEARS,KEANE,2004,1
35,36,THE JOSHUA TREE,U2,1987,1
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978,5
37,38,SCISSOR SISTERS,SCISSOR SISTERS,2004,1
38,39,BUT SERIOUSLY,PHIL COLLINS,1989,1
39,40,X&Y,COLDPLAY,2005,1
40,41,JAGGED LITTLE PILL,ALANIS MORISSETTE,1995,1
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973,1
42,43,THE MAN WHO,TRAVIS,1999,1
43,44,TRACY CHAPMAN,TRACY CHAPMAN,1988,1
44,45,PARACHUTES,COLDPLAY,2000,1
45,46,GREATEST HITS,ABBA,1975,1
46,47,GREASE,ORIGINAL SOUNDTRACK,1977,1
47,48,I'VE BEEN EXPECTING YOU,ROBBIE WILLIAMS,1998,1
48,49,X,ED SHEERAN,2014,1
49,50,COME AWAY WITH ME,NORAH JONES,2002,1
50,51,GRACELAND,PAUL SIMON,1986,1
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965,1
52,53,LADIES & GENTLEMEN - THE BEST OF,GEORGE MICHAEL,1998,1
53,54,TANGO IN THE NIGHT,FLEETWOOD MAC,1987,1
54,55,THE MARSHALL MATHERS LP,EMINEM,2000,1
55,56,SWING WHEN YOU'RE WINNING,ROBBIE WILLIAMS,2001,1
56,57,PROGRESS,TAKE THAT,2010,1
57,58,EYES OPEN,SNOW PATROL,2006,1
58,59,NEVER FORGET - THE ULTIMATE COLLECTION,TAKE THAT,2005,2
59,60,AUTOMATIC FOR THE PEOPLE,REM,1992,1

In [46]:
df = df.drop(columns=['Max poz'])  #usuniecie kolumny

In [47]:
df

,Pos,Tytuł,Artysta,Rok
0,1,GREATEST HITS,QUEEN,1981
1,2,GOLD - GREATEST HITS,ABBA,1992
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967
3,4,21,ADELE,2011
4,5,WHAT'S THE STORY MORNING GLORY,OASIS,1995
5,6,THRILLER,MICHAEL JACKSON,1982
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973
7,8,BROTHERS IN ARMS,DIRE STRAITS,1985
8,9,BAD,MICHAEL JACKSON,1987
9,10,GREATEST HITS II,QUEEN,1991
10,11,RUMOURS,FLEETWOOD MAC,1977
11,12,THE IMMACULATE COLLECTION,MADONNA,1990
12,13,BACK TO BLACK,AMY WINEHOUSE,2006
13,14,STARS,SIMPLY RED,1991
14,15,COME ON OVER,SHANIA TWAIN,1997
15,16,LEGEND,BOB MARLEY & THE WAILERS,1984
16,17,BACK TO BEDLAM,JAMES BLUNT,2004
17,18,URBAN HYMNS,VERVE,1997
18,19,BAT OUT OF HELL,MEAT LOAF,1977
19,20,1,BEATLES,2000
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970
21,22,DIRTY DANCING,ORIGINAL SOUNDTRACK,1987
22,23,SPIRIT,LEONA LEWIS,2007
23,24,CRAZY LOVE,MICHAEL BUBLE,2009
24,25,NO ANGEL,DIDO,2000
25,26,WHITE LADDER,DAVID GRAY,1998
26,27,25,ADELE,2015
27,28,TALK ON CORNERS,CORRS,1997
28,29,SPICE,SPICE GIRLS,1996
29,30,THE FAME,LADY GAGA,2008
30,31,A RUSH OF BLOOD TO THE HEAD,COLDPLAY,2002
31,32,LIFE FOR RENT,DIDO,2003
32,33,ONLY BY THE NIGHT,KINGS OF LEON,2008
33,34,BEAUTIFUL WORLD,TAKE THAT,2006
34,35,HOPES AND FEARS,KEANE,2004
35,36,THE JOSHUA TREE,U2,1987
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978
37,38,SCISSOR SISTERS,SCISSOR SISTERS,2004
38,39,BUT SERIOUSLY,PHIL COLLINS,1989
39,40,X&Y,COLDPLAY,2005
40,41,JAGGED LITTLE PILL,ALANIS MORISSETTE,1995
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973
42,43,THE MAN WHO,TRAVIS,1999
43,44,TRACY CHAPMAN,TRACY CHAPMAN,1988
44,45,PARACHUTES,COLDPLAY,2000
45,46,GREATEST HITS,ABBA,1975
46,47,GREASE,ORIGINAL SOUNDTRACK,1977
47,48,I'VE BEEN EXPECTING YOU,ROBBIE WILLIAMS,1998
48,49,X,ED SHEERAN,2014
49,50,COME AWAY WITH ME,NORAH JONES,2002
50,51,GRACELAND,PAUL SIMON,1986
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965
52,53,LADIES & GENTLEMEN - THE BEST OF,GEORGE MICHAEL,1998
53,54,TANGO IN THE NIGHT,FLEETWOOD MAC,1987
54,55,THE MARSHALL MATHERS LP,EMINEM,2000
55,56,SWING WHEN YOU'RE WINNING,ROBBIE WILLIAMS,2001
56,57,PROGRESS,TAKE THAT,2010
57,58,EYES OPEN,SNOW PATROL,2006
58,59,NEVER FORGET - THE ULTIMATE COLLECTION,TAKE THAT,2005
59,60,AUTOMATIC FOR THE PEOPLE,REM,1992

In [48]:
df['Rok'].value_counts().head(1)   #w ktorym roku bylo najwiecej albumow

Rok
1987    4
Name: count, dtype: int64

In [49]:
df[(df['Rok'] >= 1960) & (df['Rok'] <= 1990)].shape[0]  # ilosc albumow miedzy 1960 a 1990

22

In [50]:
df['Rok'].max()  #najmlodszy album

np.int64(2015)

In [51]:
earliest_albums = df.loc[df.groupby('Artysta')['Rok'].idxmin()]  #lista najwczesniej wydanych albumow kazdego artysty

In [52]:
earliest_albums.sort_values('Rok')

,Pos,Tytuł,Artysta,Rok
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973
45,46,GREATEST HITS,ABBA,1975
46,47,GREASE,ORIGINAL SOUNDTRACK,1977
18,19,BAT OUT OF HELL,MEAT LOAF,1977
10,11,RUMOURS,FLEETWOOD MAC,1977
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978
0,1,GREATEST HITS,QUEEN,1981
5,6,THRILLER,MICHAEL JACKSON,1982
15,16,LEGEND,BOB MARLEY & THE WAILERS,1984
7,8,BROTHERS IN ARMS,DIRE STRAITS,1985
50,51,GRACELAND,PAUL SIMON,1986
35,36,THE JOSHUA TREE,U2,1987
43,44,TRACY CHAPMAN,TRACY CHAPMAN,1988
38,39,BUT SERIOUSLY,PHIL COLLINS,1989
11,12,THE IMMACULATE COLLECTION,MADONNA,1990
13,14,STARS,SIMPLY RED,1991
59,60,AUTOMATIC FOR THE PEOPLE,REM,1992
4,5,WHAT'S THE STORY MORNING GLORY,OASIS,1995
40,41,JAGGED LITTLE PILL,ALANIS MORISSETTE,1995
28,29,SPICE,SPICE GIRLS,1996
27,28,TALK ON CORNERS,CORRS,1997
14,15,COME ON OVER,SHANIA TWAIN,1997
17,18,URBAN HYMNS,VERVE,1997
52,53,LADIES & GENTLEMEN - THE BEST OF,GEORGE MICHAEL,1998
25,26,WHITE LADDER,DAVID GRAY,1998
47,48,I'VE BEEN EXPECTING YOU,ROBBIE WILLIAMS,1998
42,43,THE MAN WHO,TRAVIS,1999
54,55,THE MARSHALL MATHERS LP,EMINEM,2000
44,45,PARACHUTES,COLDPLAY,2000
24,25,NO ANGEL,DIDO,2000
49,50,COME AWAY WITH ME,NORAH JONES,2002
16,17,BACK TO BEDLAM,JAMES BLUNT,2004
37,38,SCISSOR SISTERS,SCISSOR SISTERS,2004
34,35,HOPES AND FEARS,KEANE,2004
58,59,NEVER FORGET - THE ULTIMATE COLLECTION,TAKE THAT,2005
12,13,BACK TO BLACK,AMY WINEHOUSE,2006
57,58,EYES OPEN,SNOW PATROL,2006
22,23,SPIRIT,LEONA LEWIS,2007
32,33,ONLY BY THE NIGHT,KINGS OF LEON,2008
29,30,THE FAME,LADY GAGA,2008
23,24,CRAZY LOVE,MICHAEL BUBLE,2009
3,4,21,ADELE,2011
48,49,X,ED SHEERAN,2014

In [53]:
earliest_albums.to_csv('earliest_albums.csv', index=False) #zapis to pliku CSV (bez indexu)

# PIVOT TABLE

In [83]:
df = pd.read_excel('Pivot.xlsx')

In [84]:
df.head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06

In [56]:
import numpy as np

In [57]:
df.groupby(['Przedstawiciel', 'Region'])['Sprzedaż'].sum().unstack()  #tutaj jest GROUPBY

Region          Południe   Wschód   Zachód  ZachódCentrum
Przedstawiciel
Franciszek       3029.98  8919.85  1608.96            NaN
Grzegorz         2040.69  4854.15  4376.02         154.34
Krystian         2228.68  7894.56  2006.31            NaN
Patryk           5769.22  5670.96  2828.02         816.84
Paulina          1954.58  6696.10  9790.96        1449.21
Szymon           4791.80  3633.19  4168.15            NaN

In [58]:
df.pivot_table(values='Sprzedaż',index='Przedstawiciel',columns='Region',aggfunc=np.sum) #TU PIVOT

Region          Południe   Wschód   Zachód  ZachódCentrum
Przedstawiciel
Franciszek       3029.98  8919.85  1608.96            NaN
Grzegorz         2040.69  4854.15  4376.02         154.34
Krystian         2228.68  7894.56  2006.31            NaN
Patryk           5769.22  5670.96  2828.02         816.84
Paulina          1954.58  6696.10  9790.96        1449.21
Szymon           4791.80  3633.19  4168.15            NaN

In [59]:
df.pivot_table(values='Sprzedaż',index='Przedstawiciel',columns='Region',aggfunc=np.sum).fillna(0).round(2)

Region          Południe   Wschód   Zachód  ZachódCentrum
Przedstawiciel
Franciszek       3029.98  8919.85  1608.96           0.00
Grzegorz         2040.69  4854.15  4376.02         154.34
Krystian         2228.68  7894.56  2006.31           0.00
Patryk           5769.22  5670.96  2828.02         816.84
Paulina          1954.58  6696.10  9790.96        1449.21
Szymon           4791.80  3633.19  4168.15           0.00

In [60]:
df.pivot_table(values='Sprzedaż',index=['Region','Przedstawiciel'],aggfunc=np.sum).round(2).sort_values(by=['Region','Sprzedaż'],ascending=[True,False])

                              Sprzedaż
Region        Przedstawiciel
Południe      Patryk           5769.22
              Szymon           4791.80
              Franciszek       3029.98
              Krystian         2228.68
              Grzegorz         2040.69
              Paulina          1954.58
Wschód        Franciszek       8919.85
              Krystian         7894.56
              Paulina          6696.10
              Patryk           5670.96
              Grzegorz         4854.15
              Szymon           3633.19
Zachód        Paulina          9790.96
              Grzegorz         4376.02
              Szymon           4168.15
              Patryk           2828.02
              Krystian         2006.31
              Franciszek       1608.96
ZachódCentrum Paulina          1449.21
              Patryk            816.84
              Grzegorz          154.34

In [61]:
df.pivot_table(values='Sprzedaż',index='Region',aggfunc=[len,np.max,np.min]).round(0) # Tym razem będziemy chcieli poznać liczbę, maksymalną oraz minimalną wartość transakcji w rozróżnieniu na poszczególne regiony.

                   len      max      min
              Sprzedaż Sprzedaż Sprzedaż
Region
Południe            27   1512.0    115.0
Wschód              50   1675.0    153.0
Zachód              24   5001.0    132.0
ZachódCentrum        4   1449.0    154.0

# APPLY

In [62]:
def commission_fee(x):
    if x <= 300:
        return 0
    elif x < 900: 
        return x * 0.03
    else:
        return x * 0.06

In [63]:
df['commission_fee'] = df['Sprzedaż'].apply(lambda x: commission_fee(x))

In [85]:
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06
...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84

In [65]:
df['Produkt_len'] = df['Produkt'].apply(len)

In [66]:
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651,4
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8
...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,66.0084,6
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,0.0000,4
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,13.1343,8
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,20.2725,4
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,55.8894,8

In [67]:
import math

In [68]:
df['#_opakowan'] = df['Sztuki'].apply(lambda x: math.ceil(x/5))

In [69]:
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowan
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,12.9651,4,4
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,15.8550,6,5
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,24.3213,4,6
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,12.5562,6,4
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8,8
...,...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,66.0084,6,10
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,0.0000,4,2
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,13.1343,8,5
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,20.2725,4,5
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,55.8894,8,10

In [70]:
def bonus(row):

    margin = (row['Sprzedaż'] - row['Koszty'])/row['Sprzedaż']

    if margin > 0.55:
        return 200
    else:
        return 0

In [71]:
df['Bonus'] = df.apply(lambda row: bonus(row),axis =1)

In [72]:
df.sample(10)

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,commission_fee,Produkt_len,#_opakowan,Bonus
84,2020-01-24,Quad,Zachód,Grzegorz,HII,63,1701.68,913.74,102.1008,4,13,0
81,2020-01-23,Quad,Wschód,Paulina,WT,22,594.17,319.41,17.8251,4,5,0
96,2020-01-28,Bellen,Południe,Szymon,QT,25,550.39,250.46,16.5117,6,5,0
67,2020-01-20,Sunshine,Zachód,Szymon,YTR,58,1102.81,464.06,66.1686,8,12,200
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,21.6666,8,8,200
48,2020-01-16,Carlota,Południe,Patryk,QT,31,713.28,341.34,21.3984,7,7,0
49,2020-01-17,Quad,Wschód,Franciszek,HII,62,1674.82,899.56,100.4892,4,13,0
41,2020-01-13,Sunshine,Wschód,Paulina,PSA,33,627.32,264.54,18.8196,8,7,200
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,13.1343,8,5,200
80,2020-01-23,Bellen,Wschód,Grzegorz,DFGH,9,198.06,90.45,0.0000,6,2,0

# MAP

In [73]:
car_dict = dict(zip(df['Przedstawiciel'].unique(),['Mazda','Toyota','BMW','Audi','Fiat','Seat']))

In [74]:
print(car_dict)

{'Szymon': 'Mazda', 'Grzegorz': 'Toyota', 'Paulina': 'BMW', 'Krystian': 'Audi', 'Franciszek': 'Fiat', 'Patryk': 'Seat'}

In [86]:
df['Marka_samochodu'] = df['Przedstawiciel'].map(car_dict)

In [87]:
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,Marka_samochodu
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,Mazda
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,Toyota
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,BMW
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,BMW
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,BMW
...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,Audi
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,Toyota
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,Mazda
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,Mazda
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,Toyota

In [94]:
RegionKraj_dict ={
    'Wschód':'Poland',
    'Zachód': 'Germany',
    'Północ':'Sweden',
    'Południe':'Italy'
}

In [95]:
df['Region_Kraj'] =df['Region'].map(RegionKraj_dict)

In [96]:
df

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,Marka_samochodu,Region_Kraj
0,2020-01-01,Quad,Wschód,Szymon,AA,16,432.17,232.99,Mazda,Poland
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,Toyota,Italy
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,BMW,Germany
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,BMW,Germany
4,2020-01-03,Sunshine,Wschód,Paulina,FM,38,722.22,304.06,BMW,Poland
...,...,...,...,...,...,...,...,...,...,...
100,2020-01-29,Bellen,Wschód,Krystian,AST,50,1100.14,500.16,Audi,Poland
101,2020-01-29,Quad,Wschód,Grzegorz,PLOT,10,270.50,145.57,Toyota,Poland
102,2020-01-30,Sunshine,Południe,Szymon,TTT,23,437.81,184.16,Mazda,Italy
103,2020-01-30,Quad,Południe,Szymon,TTT,25,675.75,362.89,Mazda,Italy
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,Toyota,Germany

In [99]:
df['Data'] = pd.to_datetime(df['Data'])

In [100]:
df['Data'].dt.day_name().head()

0    Wednesday
1     Thursday
2     Thursday
3     Thursday
4       Friday
Name: Data, dtype: str

In [101]:
df['Data'].dt.month_name().head()

0    January
1    January
2    January
3    January
4    January
Name: Data, dtype: str

In [102]:
df['Data'].dt.is_month_start.head()

0     True
1    False
2    False
3    False
4    False
Name: Data, dtype: bool

In [103]:
df[df['Data'].dt.day_name()=='Thursday'].head()

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,Marka_samochodu,Region_Kraj
1,2020-01-02,Bellen,Południe,Grzegorz,KBTB,24,528.50,240.35,Toyota,Italy
2,2020-01-02,Quad,Zachód,Paulina,AST,30,810.71,435.64,BMW,Germany
3,2020-01-02,Bellen,Zachód,Paulina,SFWK,19,418.54,190.05,BMW,Germany
22,2020-01-09,Carlota,Wschód,Franciszek,WSD,38,874.45,418.69,Fiat,Poland
23,2020-01-09,Bellen,Wschód,Paulina,EPP,40,880.38,400.89,BMW,Poland

In [105]:
df['Produkt'].str.upper().head()

0        QUAD
1      BELLEN
2        QUAD
3      BELLEN
4    SUNSHINE
Name: Produkt, dtype: str

In [106]:
df['Region'].str.endswith('ód').head()

0     True
1    False
2     True
3     True
4     True
Name: Region, dtype: bool

In [107]:
df[df['Region'].str.contains('Zachód')].sample(5)

,Data,Produkt,Region,Przedstawiciel,Klient,Sztuki,Sprzedaż,Koszty,Marka_samochodu,Region_Kraj
104,2020-01-30,Sunshine,Zachód,Grzegorz,DFR,49,931.49,392.84,Toyota,Germany
76,2020-01-22,Bellen,Zachód,Paulina,AST,53,1166.31,530.24,BMW,Germany
11,2020-01-05,Carlota,Zachód,Franciszek,ITTW,60,1380.07,660.40,Fiat,Germany
29,2020-01-10,Quad,ZachódCentrum,Patryk,DFR,17,459.29,246.75,Seat,NaN
30,2020-01-10,Sunset,ZachódCentrum,Patryk,MBG,17,357.55,157.95,Seat,NaN