In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({
    'e1': [80, 85, 90],
    'e2': [75, 88, 92]
}, index=['Student A', 'Student B', 'Student C'])

df.loc['Student B']

e1    85
e2    88
Name: Student B, dtype: int64

In [8]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92

In [13]:
df.loc['Student X'] = [90,1]

In [11]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92
Student X  90   1

In [1]:
import pandas as pd

left = pd.DataFrame({
    'user_id': [1, 2, 3],
    'name': ['Adam', 'Ewa', 'Jan']
})

right = pd.DataFrame({
    'user_id': [1, 2, 4],
    'score': [100, 200, 300]
})

In [2]:
left
right

   user_id  score
0        1    100
1        2    200
2        4    300

In [18]:
right

  category_name
1          food
2          tech
3       clothes

In [4]:
left

   user_id  name
0        1  Adam
1        2   Ewa
2        3   Jan

In [5]:
#pd.merge(left,right,how="inner",on='key')  #innerJoin

In [17]:
left.merge(right, on='user_id', how='left')

KeyError: 'user_id'

In [9]:
active_users

   user_id
0       10
1       30

In [10]:
orders.merge(active_users[['user_id']], on='user_id')

   order_id  user_id
0         1       10
1         3       30

In [11]:
left = pd.DataFrame({
    'product': ['A','B','C'],
    'category_id': [1,2,3]
})

right = pd.DataFrame({
    'category_name': ['food','tech','clothes']
}, index=[1,2,3])

In [12]:
left

  product  category_id
0       A            1
1       B            2
2       C            3

In [13]:
right

  category_name
1          food
2          tech
3       clothes

In [14]:
left.join(right,on='category_id')

  product  category_id category_name
0       A            1          food
1       B            2          tech
2       C            3       clothes