In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'e1': [80, 85, 90],
    'e2': [75, 88, 92]
}, index=['Student A', 'Student B', 'Student C'])

df.loc['Student B']

e1    85
e2    88
Name: Student B, dtype: int64

In [4]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92

In [5]:
df.loc['Student X'] = [90,1]

In [6]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92
Student X  90   1

In [7]:
import pandas as pd

left = pd.DataFrame({
    'user_id': [1, 2, 3],
    'name': ['Adam', 'Ewa', 'Jan']
})

right = pd.DataFrame({
    'user_id': [1, 2, 4],
    'score': [100, 200, 300]
})

In [8]:
left
right

   user_id  score
0        1    100
1        2    200
2        4    300

In [9]:
right

   user_id  score
0        1    100
1        2    200
2        4    300

In [10]:
left

   user_id  name
0        1  Adam
1        2   Ewa
2        3   Jan

In [11]:
#pd.merge(left,right,how="inner",on='key')  #innerJoin

In [12]:
left.merge(right, on='user_id', how='left')

   user_id  name  score
0        1  Adam  100.0
1        2   Ewa  200.0
2        3   Jan    NaN

In [13]:
active_users

NameError: name 'active_users' is not defined

In [ ]:
orders.merge(active_users[['user_id']], on='user_id')

In [ ]:
left = pd.DataFrame({
    'product': ['A','B','C'],
    'category_id': [1,2,3]
})

right = pd.DataFrame({
    'category_name': ['food','tech','clothes']
}, index=[1,2,3])

In [ ]:
left

In [ ]:
right

In [ ]:
left.join(right,on='category_id')

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Pivot.xlsx')

In [ ]:
df.head()

In [ ]:
def poziom_sprzedazy(x):
    if x < 300:
        return 'niska'
    elif x > 900:
        return 'wysoka'
    else:
        return 'srednia'

In [ ]:
df['Poziom_sprzedazy'] = df['Sprzedaż'].apply(lambda x: poziom_sprzedazy(x))

In [ ]:
df

In [ ]:
#zadanie 2

In [ ]:
df['Product_upper'] = df.Produkt.apply.upper()

In [ ]:
import math

In [ ]:
def rabat(x):

    if x > 1000:
        return x *0.1
    else:
        return x *0.05

In [ ]:
df['Rabat'] = df['Sprzedaż'].apply(lambda x: rabat(x))

In [ ]:
df

In [ ]:
df['Produkt_clean'] = df['Produkt'].str.strip().str.lower()

In [ ]:
df

In [ ]:
df['Marża_%'] = ((df['Sprzedaż'] - df['Koszty']) / df['Sprzedaż']).round(2)

In [16]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92
Student X  90   1

In [ ]:
def ocena(row):
    # liczymy marżę dla wiersza
    marza = (row['Sprzedaż'] - row['Koszty']) / row['Sprzedaż']
    
    # klasyfikacja
    if marza > 0.5:
        return 'TOP'
    elif marza >= 0.2:
        return 'OK'
    else:
        return 'LOW'

# axis=1 → działamy na wierszach
df['Ocena'] = df.apply(ocena, axis=1)

In [14]:
RegionKraj_dict ={
    'East':'Poland',
    'West': 'Germany',
    'North':'Sweden'
}

In [15]:
df['Region_Kraj'] =df['Region'].map(RegioKraj_dict)

KeyError: 'Region'

In [ ]:
df