In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({
    'e1': [80, 85, 90],
    'e2': [75, 88, 92]
}, index=['Student A', 'Student B', 'Student C'])

df.loc['Student B']

e1    85
e2    88
Name: Student B, dtype: int64

In [8]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92

In [13]:
df.loc['Student X'] = [90,1]

In [11]:
df

           e1  e2
Student A  80  75
Student B  85  88
Student C  90  92
Student X  90   1