In [46]:
import pandas as pd

In [47]:
import numpy as np

#SERIES

In [48]:
exam1 = [86,84,92,98]

In [49]:
labels = ['Student A','Student B','Student C','Student D']

In [50]:
pd.Series(exam1,labels)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [51]:
pd.Series(exam1,labels)['Student D']

np.int64(98)

# Tworzymy słownik, gdzie:
# s = element z listy labels (klucz)
# p = odpowiadający element z listy exam1 (wartość)
# zip łączy obie listy w pary (s, p)

In [52]:
d = {s:p for s,p in zip(labels,exam1)} #funkcja zip łączy dwa zbiory w pary.

In [53]:
d

{'Student A': 86, 'Student B': 84, 'Student C': 92, 'Student D': 98}

In [54]:
pd.Series(d)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [55]:
exam2 = [74,56,44,92]

In [56]:
e1=pd.Series(exam1,labels)

In [57]:
e2=pd.Series(exam2,labels)

In [58]:
e1 + e2

Student A    160
Student B    140
Student C    136
Student D    190
dtype: int64

In [59]:
e1 * e2

Student A    6364
Student B    4704
Student C    4048
Student D    9016
dtype: int64

In [60]:
e1 - e2

Student A    12
Student B    28
Student C    48
Student D     6
dtype: int64

In [61]:
e1 / e2

Student A    1.162162
Student B    1.500000
Student C    2.090909
Student D    1.065217
dtype: float64

#DataFrame

In [62]:
df=pd.DataFrame({'e1':exam1, 'e2':exam2}, index=labels)

In [63]:
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [64]:
type(df['e1'])

pandas.Series

In [65]:
data = np.array([exam1,exam2])

In [66]:
data.transpose()

array([[86, 74],
       [84, 56],
       [92, 44],
       [98, 92]])

In [67]:
df = pd.DataFrame(data.transpose(),index=labels,columns=['e1','e2'])
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [68]:
df.to_numpy() #DataFrame możemy przekształcić w drugą stronę, to znaczy zamienić DataFrame na ndarray.

array([[86, 74],
       [84, 56],
       [92, 44],
       [98, 92]])

Series przechowuje dane jednego typu, jednak DataFrame to połączenie różnych Series. W związku z tym w DataFrame mogą pojawić się dane o różnym typie. We wcześniejszym module mogliśmy zobaczyć, że cała tablica ndarray posiada dane jednego typu. Jeśli masz DataFrame, dla których jedna Series to object, a pozostałe 99 Series to float, to taki DataFrame przekształcony w ndarray będzie posiadał wszystkie dane typu object.

In [69]:
df['e3'] = [67,59,79,84]

In [70]:
df

           e1  e2  e3
Student A  86  74  67
Student B  84  56  59
Student C  92  44  79
Student D  98  92  84

In [72]:
df ['semestr1'] = df['e1'] + df['e2'] + df['e3']

In [73]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

METODA LOC

In [74]:
df.loc['Student C']

e1           92
e2           44
e3           79
semestr1    215
Name: Student C, dtype: int64

In [75]:
df.loc['Student C','e2'] #indexing

np.int64(44)

In [76]:
df.loc[['Student C','Student D'],['e2']] #fancy indexing

           e2
Student C  44
Student D  92

METODA ILOC

In [77]:
df.iloc[1]

e1           84
e2           56
e3           59
semestr1    199
Name: Student B, dtype: int64

In [79]:
df.loc['Student C']

e1           92
e2           44
e3           79
semestr1    215
Name: Student C, dtype: int64

In [80]:
df.iloc[1:,1] #SLICING

Student B    56
Student C    44
Student D    92
Name: e2, dtype: int64

Masking na podstawie wyrażeń logicznych

In [81]:
df['e2'] > 70

Student A     True
Student B    False
Student C    False
Student D     True
Name: e2, dtype: bool

In [82]:
df[df['e2'] > 70]

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student D  98  92  84       274

In [85]:
df[(df['e2']<50)|(df['e2']>90)]

           e1  e2  e3  semestr1
Student C  92  44  79       215
Student D  98  92  84       274

In [86]:
df[(df['e2']<50)|(df['e3']>90)]

           e1  e2  e3  semestr1
Student C  92  44  79       215

#USUWANIE WIERSZY - DROP + inplace=True

In [87]:
df.drop('semestr1',axis=1)

           e1  e2  e3
Student A  86  74  67
Student B  84  56  59
Student C  92  44  79
Student D  98  92  84

In [88]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

Po wykonaniu tej operacji wywołajmy jeszcze raz zmienną df w komórce poniżej, a zauważmy, że kolumna w dalszym ciągu tam jest i ma się dobrze!Dzieje się tak, ponieważ wykonując funkcję drop, nie ustawiliśmy wartości True dla parametru Inplace. Parametr ten jest swego rodzaju zaworem bezpieczeństwa, który pozwala nam wykonać jakąś operację bez rzeczywistej ingerencji we wprowadzoną wcześniej tabelę. Musimy w tym miejscu powiedzieć, że wiele funkcji Pandas działa właśnie w ten sposób, a parametr Inplace będzie przewijał się w trakcie tego szkolenia również przy innych modyfikacjach DataFrame.

Usuńmy zatem kolumny z tabeli przypisanej do zmiennej df raz na zawsze. Jednak tym razem na potrzeby przykładu razem z kolumną semester1 usuńmy kolumnę e3. W tym celu, jako pierwszy argument funkcji drop musimy wprowadzić listę kolumn do usunięcia.

In [90]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

In [92]:
df.drop(['e3','semestr1'],axis=1,inplace=True)

In [93]:
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [94]:
df.drop('Student B',inplace=True)
df

           e1  e2
Student A  86  74
Student C  92  44
Student D  98  92

#RESETOWANIE INDEKSU

In [96]:
df.reset_index() # jeśli chcemy zachować zmiany, musimy użyć parametru inplace

       index  e1  e2
0  Student A  86  74
1  Student C  92  44
2  Student D  98  92