In [168]:
import pandas as pd

In [169]:
import numpy as np

In [170]:
import missingno as msno

#SERIES

In [88]:
exam1 = [86,84,92,98]

In [89]:
labels = ['Student A','Student B','Student C','Student D']

In [90]:
pd.Series(exam1,labels)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [91]:
pd.Series(exam1,labels)['Student D']

np.int64(98)

# Tworzymy słownik, gdzie:
# s = element z listy labels (klucz)
# p = odpowiadający element z listy exam1 (wartość)
# zip łączy obie listy w pary (s, p)

In [92]:
d = {s:p for s,p in zip(labels,exam1)} #funkcja zip łączy dwa zbiory w pary.

In [93]:
d

{'Student A': 86, 'Student B': 84, 'Student C': 92, 'Student D': 98}

In [94]:
pd.Series(d)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [95]:
exam2 = [74,56,44,92]

In [96]:
e1=pd.Series(exam1,labels)

In [97]:
e2=pd.Series(exam2,labels)

In [98]:
e1 + e2

Student A    160
Student B    140
Student C    136
Student D    190
dtype: int64

In [ ]:
e1 * e2

In [ ]:
e1 - e2

In [ ]:
e1 / e2

#DataFrame

In [ ]:
df=pd.DataFrame({'e1':exam1, 'e2':exam2}, index=labels)

In [ ]:
df

In [ ]:
type(df['e1'])

In [ ]:
data = np.array([exam1,exam2])

In [ ]:
data.transpose()

In [ ]:
df = pd.DataFrame(data.transpose(),index=labels,columns=['e1','e2'])
df

In [ ]:
df.to_numpy() #DataFrame możemy przekształcić w drugą stronę, to znaczy zamienić DataFrame na ndarray.

Series przechowuje dane jednego typu, jednak DataFrame to połączenie różnych Series. W związku z tym w DataFrame mogą pojawić się dane o różnym typie. We wcześniejszym module mogliśmy zobaczyć, że cała tablica ndarray posiada dane jednego typu. Jeśli masz DataFrame, dla których jedna Series to object, a pozostałe 99 Series to float, to taki DataFrame przekształcony w ndarray będzie posiadał wszystkie dane typu object.

In [ ]:
df['e3'] = [67,59,79,84]

In [ ]:
df

In [ ]:
df ['semestr1'] = df['e1'] + df['e2'] + df['e3']

In [ ]:
df

METODA LOC

In [ ]:
df.loc['Student C']

In [ ]:
df.loc['Student C','e2'] #indexing

In [ ]:
df.loc[['Student C','Student D'],['e2']] #fancy indexing

METODA ILOC

In [ ]:
df.iloc[1]

In [ ]:
df.loc['Student C']

In [ ]:
df.iloc[1:,1] #SLICING

Masking na podstawie wyrażeń logicznych

In [ ]:
df['e2'] > 70

In [ ]:
df[df['e2'] > 70]

In [ ]:
df[(df['e2']<50)|(df['e2']>90)]

In [ ]:
df[(df['e2']<50)|(df['e3']>90)]

#USUWANIE WIERSZY - DROP + inplace=True

In [ ]:
df.drop('semestr1',axis=1)

In [ ]:
df

Po wykonaniu tej operacji wywołajmy jeszcze raz zmienną df w komórce poniżej, a zauważmy, że kolumna w dalszym ciągu tam jest i ma się dobrze!Dzieje się tak, ponieważ wykonując funkcję drop, nie ustawiliśmy wartości True dla parametru Inplace. Parametr ten jest swego rodzaju zaworem bezpieczeństwa, który pozwala nam wykonać jakąś operację bez rzeczywistej ingerencji we wprowadzoną wcześniej tabelę. Musimy w tym miejscu powiedzieć, że wiele funkcji Pandas działa właśnie w ten sposób, a parametr Inplace będzie przewijał się w trakcie tego szkolenia również przy innych modyfikacjach DataFrame.

Usuńmy zatem kolumny z tabeli przypisanej do zmiennej df raz na zawsze. Jednak tym razem na potrzeby przykładu razem z kolumną semester1 usuńmy kolumnę e3. W tym celu, jako pierwszy argument funkcji drop musimy wprowadzić listę kolumn do usunięcia.

In [ ]:
df

In [ ]:
df.drop(['e3','semestr1'],axis=1,inplace=True)

In [ ]:
df

In [ ]:
df.drop('Student B',inplace=True)
df

#RESETOWANIE INDEKSU

In [ ]:
df.reset_index() # jeśli chcemy zachować zmiany, musimy użyć parametru inplace

In [ ]:
df

In [ ]:
df = df.reindex(['Student A', 'Student B', 'Student C', 'Student D'])  #dodanie brakującego studenta

In [ ]:
df

In [ ]:
df['e3'] = [70, 85, 90, 88]

In [ ]:
df

In [ ]:
df.loc['Student B', 'e1'] = 82
df.loc['Student B', 'e2'] = 77

In [ ]:
df

In [ ]:
df ['semestr1'] = df['e1'] + df['e2'] + df['e3']

In [ ]:
df

#ZMIANA INDEXU

In [ ]:
df_new_index = df.reset_index()
df_new_index

In [ ]:
df_new_index['student_name'] = ['Marek','Michal','Oskar','Kamil']

In [ ]:
df_new_index

In [ ]:
df_new_index.set_index('student_name')

#drugi sposob na zmiane indexu

In [ ]:
df_new_index2 = df.reset_index()

In [ ]:
df_new_index

In [ ]:
df_new_index.drop(['student_name'],axis=1,inplace=True)

In [ ]:
df_new_index

In [ ]:
df_new_index2.index = ['Marek','Michal','Oskar','Kamil']

In [ ]:
df_new_index2

#RENAME

In [ ]:
df.rename(columns={'e1':'exam1','e2':'exam2','e3':'exam3'})

In [ ]:
#rename z zastosawanie funkcji

In [ ]:
df.rename(str.upper, axis='columns')

#Unique, value_counts, sort_values, drop_duplicates

In [ ]:
df = pd.DataFrame({'A':[100,44,56,99,85,100],
                  'B':['Panda','Snake','Snake','Rat','Dog','Panda']})

In [ ]:
df

In [ ]:
df['B'].unique()

In [ ]:
df['B'].nunique()

In [ ]:
df['B'].value_counts()

In [ ]:
df['B'].value_counts(normalize=True)   #% udział

In [ ]:
df.sort_values(by='A')  #sortowanie

In [ ]:
df.sort_values(by='A',ascending=False)

In [ ]:
df.drop_duplicates() #usun_duplikaty

M U L T I_I D E X

In [ ]:
exam1 = [89,85,93,83]
exam2 = [74,56,44,92]
exam3=[67,59,79,84]
df = pd.DataFrame({'e1':exam1, 'e2':exam2, 'e3':exam3}, index=labels)
df['semester1'] = df['e1']+df['e2']+df['e3']

In [ ]:
df

pierwszy sposob - MultiIndex.from_tuples

In [ ]:
schools = ['High School X','High School X','High School Y','High School Y']
multi_index_list = [(school,student) for school,student in zip(schools,df.index)]
multi_index_list

In [ ]:
df.index = pd.MultiIndex.from_tuples(multi_index_list,names=['School','Student'])
df

drugi sposob - funkcja set_index

In [ ]:
df.set_index([pd.Index(['High School X','High School X','High School Y','High School Y']), df.index],inplace=True)

In [ ]:
df

In [ ]:
df.set_index.names = ['School','Student']
df

In [ ]:
len(df)

In [ ]:
len(['High School X','High School X','High School Y','High School Y'])

In [ ]:
df.index.nlevels

In [ ]:
print(df.index.names)

In [ ]:
df = df.reset_index(drop=True)

df.index = pd.MultiIndex.from_arrays(
    [
        ['High School X','High School X','High School Y','High School Y'],
        df.index
    ],
    names=['School','Student']
)

In [ ]:
df

In [ ]:
df.loc['High School X']

In [ ]:
df = df.reset_index()

In [ ]:
df['Student'] = ['Student A','Student B','Student C','Student D']

In [ ]:
df = df.set_index(['School', 'Student', 'e1', 'e2', 'e3', 'semester1'])

In [ ]:
df

In [ ]:
df.loc['High School X']

In [ ]:
df.loc['High School X'].iloc[1]

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.loc['High School X']

In [ ]:
df.columns

In [ ]:
df = df.reset_index()

In [ ]:
df = df.set_index(['School','Student'])

In [ ]:
df

In [ ]:
df.index
df.index.names

In [ ]:
df.loc['High School X'].iloc[1]

In [ ]:
df.xs('High School Y')

In [ ]:
df.xs(('High School Y','Student D'))

In [ ]:
df.xs('Student D',level='Student')

Ćwiczenie
Do tabeli przypisanej do zmiennej df dodaj kolumny: e4, e5, e6. Niech wektory tych kolumn odzwierciedlają wyniki z kolejnych egzaminów w drugim semestrze Studentów A, B, C oraz D. Wyniki tych egzaminów niech będą losowane z liczb całkowitych o zakresie 1-100 włącznie. Następnie usuń kolumnę semester1. Po wykonaniu tych operacji stwórz indeks hierarchiczny dla kolumn tabeli, tak aby jego najwyższym rzędem było oznaczenie semestru, w którym napisany był dany egzamin.

In [ ]:
df['e4']=np.random.randint(1,101,size=len(df))

In [ ]:
df['e5']=np.random.randint(1,101,size=len(df))
df['e6']=np.random.randint(1,101,size=len(df))

In [ ]:
df

In [ ]:
df.drop(columns='semester1', inplace=True)   #usuniecie kolumny

In [ ]:
df

 Zbudowanie MultiIndex dla kolumn
(Semestr → Egzamin)

In [ ]:
cols = pd.MultiIndex.from_tuples(
    [
        ('Semestr 1','e1'),
        ('Semestr 1','e2'),
        ('Semestr 1','e3'),
        ('Semestr 2','e4'),
        ('Semestr 2','e5'),
        ('Semestr 2','e6'),
    ],
    names=['Semestr','Egzamin']
)

In [ ]:
df.columns = cols

In [ ]:
df

In [ ]:
df['Semestr 1']

In [ ]:
df['Semestr 2']['e5']

# GROUPBY

In [ ]:
df = pd.DataFrame({'Category':['Games','Games','Games',

                               'Film&Video','Film&Video','Film&Video'],

                  'Project_Title':['The Last Faith','Magic Puzzles','Dinosaur Fossil Hunter',

                                   'Beyond Your Eyes','5150','8-Bit Wars'],

                  'Pledged':[92774,2873519,7962,

                             276,23963,6950],

                  'Country':['UK','USA','Poland',

                             'Bulgaria','USA','UK'],

                  'Date_Start':['2020-03-21','2020-03-11','2020-04-16',

                                '2020-02-09','2020-04-10','2020-03-19']})

In [ ]:
df

In [ ]:
df.groupby('Category')

Jeśli wywołamy funkcję Groupby i wskażemy tylko kolumnę, według której chcemy wykonać grupowanie, otrzymamy z powrotem jedynie informację o miejscu w pamięci, gdzie możemy znaleźć obiekt Groupby. Jeśli chcemy otrzymać z powrotem pogrupowany DataFrame, musimy wykonać funkcję agregującą informacje w wierszac

In [ ]:
df.groupby('Category').sum()

In [ ]:
df.groupby('Category')['Pledged'].sum()

In [ ]:
df.groupby('Category')['Pledged'].mean()

In [ ]:
df.groupby('Category').count()

In [ ]:
df['Date_Start'] = pd.to_datetime(df['Date_Start'])

In [ ]:
df

In [ ]:
df.groupby(pd.Grouper(key='Date_Start',freq='ME')).sum()

Rozwijając problem, który rozwiązaliśmy w poprzednim przykładzie, spróbujemy teraz jednym poleceniem zgrupować projekty według miesiąca ‘Date_Start’, tak aby oprócz zebranej dotychczas sumy mieć obok informację o liczbie składających się na nią projektów.

W tym celu, zamiast podawać jedną funkcję agregującą, wykorzystamy agg, w której sprecyzujemy sposób agregowania każdej kolumny.

In [ ]:
df.groupby(pd.Grouper(key='Date_Start',freq='ME')).agg({'Pledged':'sum','Project_Title':'count'})

In [ ]:
df.groupby(['Country','Category',])['Pledged'].sum() #to zwraca series

In [ ]:
df.groupby(['Country','Category'], as_index=False)['Pledged'].sum() # a to DF

In [ ]:
df.groupby(['Country','Category']).agg({'Pledged':'sum'})

In [ ]:
df.index.names

In [ ]:
df.groupby('Country')['Pledged'].mean().sort_values(ascending=False).head(1)

In [ ]:
df.groupby('Category')['Project_Title'].count()

In [ ]:
df.groupby('Category')['Pledged'].sum().sort_values(ascending=False).head(1)

In [ ]:
df.loc[df.groupby('Country')['Pledged'].idxmax()]

# BRAKUJACE DANE

In [ ]:
df_with_nulls = pd.DataFrame({'A':[1,100,np.nan,1000,10000],
                             'B':[2,4,2,4,np.nan],
                             'C':[40,np.nan,20,np.nan,np.nan]})
df_with_nulls

In [ ]:
print(df_with_nulls.isnull().mean())
print()
print(df_with_nulls.isnull().sum())

In [ ]:
df_with_nulls[df_with_nulls['C'].isnull()]

#DROPNA

In [ ]:
msno.matrix(df_with_nulls)

In [ ]:
df_with_nulls

In [ ]:
df_with_nulls.dropna()

TRESH - minimalną liczbę uzupełnionych wartości w wierszu, która kwalifikuje go do pozostania w tabeli.

In [ ]:
df_with_nulls.dropna(thresh=2)

In [ ]:
df_with_nulls.dropna(thresh=3,axis=1) # mozna wyrzucac ten kolumny

In [ ]:
df_with_nulls.fillna('NOWA WARTOŚĆ')

In [ ]:
df_with_nulls['B'].fillna(df_with_nulls['B'].mean())  #uzupelnienie brakujacych wartosci na podstawie sredniej wartosci z danej kolumny

In [ ]:
df_with_nulls['A'].ffill()

In [ ]:
df_with_nulls['A'].bfill()

In [ ]:
# zeby zmienilo dane df_with_nulls['A'] = df_with_nulls['A'].bfill()

In [171]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],

                    'B': ['B0', 'B1', 'B2', 'B3'],

                    'C': ['C0', 'C1', 'C2', 'C3'],

                    'D': ['D0', 'D1', 'D2', 'D3']},

                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],

                    'B': ['B4', 'B5', 'B6', 'B7'],

                    'C': ['C4', 'C5', 'C6', 'C7'],

                    'D': ['D4', 'D5', 'D6', 'D7']},

                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],

                    'B': ['B8', 'B9', 'B10', 'B11'],

                    'C': ['C8', 'C9', 'C10', 'C11'],

                    'D': ['D8', 'D9', 'D10', 'D11']},

                    index=[8, 9, 10, 11])

In [172]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [173]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# CONCATENATE

In [ ]:
pd.concat([df1,df2,df3])

In [ ]:
pd.concat([df1,df2,df3],axis=1)

In [ ]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s])

In [ ]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s],axis=1)

In [ ]:
pd.concat([df1,df2,df3],axis=1,keys=['first','second','third'])

In [ ]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s])

Ćwiczenie
Połącz ze sobą df1, df2, df3 wzdłuż osi poziomej używając funkcji concat. Postaraj się, aby połączona tabela nie rozszerzała się na dodatkowe wiersze w dół.

In [ ]:


# reset indexów
df1_reset = df1.reset_index(drop=True)
df2_reset = df2.reset_index(drop=True)
df3_reset = df3.reset_index(drop=True)

# concat poziomy
result = pd.concat([df1_reset, df2_reset, df3_reset], axis=1)

print(result)

-reset_index(drop=True) → ustawia index 0,1,2,3 dla wszystkich
-axis=1 → łączenie w poziomie (kolumny)
-dzięki temu pandas nie dodaje nowych wierszy

# MERGE

In [174]:
def make_keys(n):
    return [f'key{n}' for n in range(n)]
left = df1.copy()
left['key'] = make_keys(4)
right = df3.copy()
right['key'] = make_keys(4)

In [175]:
print(left)

    A   B   C   D   key
0  A0  B0  C0  D0  key0
1  A1  B1  C1  D1  key1
2  A2  B2  C2  D2  key2
3  A3  B3  C3  D3  key3

In [176]:
print(right)

      A    B    C    D   key
8    A8   B8   C8   D8  key0
9    A9   B9   C9   D9  key1
10  A10  B10  C10  D10  key2
11  A11  B11  C11  D11  key3

In [178]:
pd.merge(left,right,how="inner",on='key')  #innerJoin

  A_x B_x C_x D_x   key  A_y  B_y  C_y  D_y
0  A0  B0  C0  D0  key0   A8   B8   C8   D8
1  A1  B1  C1  D1  key1   A9   B9   C9   D9
2  A2  B2  C2  D2  key2  A10  B10  C10  D10
3  A3  B3  C3  D3  key3  A11  B11  C11  D11

In [179]:
new_right=pd.DataFrame({'E':['E1','E2','E3','E4','E5','E6'],'key':make_keys(6)})

In [180]:
new_right

    E   key
0  E1  key0
1  E2  key1
2  E3  key2
3  E4  key3
4  E5  key4
5  E6  key5

In [182]:
pd.merge(left,new_right,how='inner',on='key') #laczmy tabele left i tabele new_right - sposob inner , klucz key

    A   B   C   D   key   E
0  A0  B0  C0  D0  key0  E1
1  A1  B1  C1  D1  key1  E2
2  A2  B2  C2  D2  key2  E3
3  A3  B3  C3  D3  key3  E4

In [184]:
pd.merge(left,new_right,how='outer',on='key') #tutaj mamy outer - czyli bierzemy wszystko z obu tabel,jesli nie czegos w jednej to dostajemy NaN - w sensie nie ma tych samych kluczy ( elementow laczacych)

     A    B    C    D   key   E
0   A0   B0   C0   D0  key0  E1
1   A1   B1   C1   D1  key1  E2
2   A2   B2   C2   D2  key2  E3
3   A3   B3   C3   D3  key3  E4
4  NaN  NaN  NaN  NaN  key4  E5
5  NaN  NaN  NaN  NaN  key5  E6

# JOIN

Funkcja join działa w zbliżony do merge sposób. Jako jedyna z trzech omawianych w tym rozdziale funkcji jest wykonywana bezpośrednio na obiekcie DataFrame, do którego przyłączana ma być inna tabela.

Trzeba jednak pamiętać, że przyłączana tabela będzie się łączyć zawsze po swoim indeksie. Jednakże kluczem z tabeli, do której będziemy przyłączać inną może być dowolna kolumna.

In [185]:
other = pd.DataFrame({'E':['E1','E2','E3','E4','E5','E6']},index=['B1','B2','B3','B4','B5','B6'])

In [192]:
print (other)
print (left)

     E
B1  E1
B2  E2
B3  E3
B4  E4
B5  E5
B6  E6
    A   B   C   D   key
0  A0  B0  C0  D0  key0
1  A1  B1  C1  D1  key1
2  A2  B2  C2  D2  key2
3  A3  B3  C3  D3  key3

Zauważmy, że left i other nie łączy wspólny indeks. Ich punktem wspólnym są z kolei kolumna ‘B’ w left oraz indeks w other. W takim wypadku możemy użyć funkcji join, aby je ze sobą połączyć.

In [195]:
left.join(other,on='B') #left jest domyślny

    A   B   C   D   key    E
0  A0  B0  C0  D0  key0  NaN
1  A1  B1  C1  D1  key1   E1
2  A2  B2  C2  D2  key2   E2
3  A3  B3  C3  D3  key3   E3

In [194]:
left.join(other,on='B',how='inner')

    A   B   C   D   key   E
1  A1  B1  C1  D1  key1  E1
2  A2  B2  C2  D2  key2  E2
3  A3  B3  C3  D3  key3  E3

CWICZENIE Użyj funkcji join, aby połączyć ze sobą tabele left oraz right według kolumny key.

In [200]:
left

    A   B   C   D   key
0  A0  B0  C0  D0  key0
1  A1  B1  C1  D1  key1
2  A2  B2  C2  D2  key2
3  A3  B3  C3  D3  key3

In [201]:
right

      A    B    C    D   key
8    A8   B8   C8   D8  key0
9    A9   B9   C9   D9  key1
10  A10  B10  C10  D10  key2
11  A11  B11  C11  D11  key3

In [203]:
#left.join(right,on='key')  #zeby zrobic JOIN jeden z elementow musi byc indexem <<<<(inaczej blad)

In [208]:
#left.join(right.set_index('key'), on='key') #Błąd jest bardzo konkretny i mówi dokładnie, co się dzieje:

#👉 masz te same nazwy kolumn w obu DataFrame’ach (A, B, C, D)
#👉 i nie podałeś suffixów, więc pandas nie wie, jak je rozróżnić

In [212]:
left.join(
    right.set_index('key'),
    on='key',
    lsuffix='_left',
    rsuffix='_right')#jak dodalismy suffix to dziala

  A_left B_left C_left D_left   key A_right B_right C_right D_right
0     A0     B0     C0     D0  key0      A8      B8      C8      D8
1     A1     B1     C1     D1  key1      A9      B9      C9      D9
2     A2     B2     C2     D2  key2     A10     B10     C10     D10
3     A3     B3     C3     D3  key3     A11     B11     C11     D11

In [213]:
left.merge(right[['key']], on='key')

    A   B   C   D   key
0  A0  B0  C0  D0  key0
1  A1  B1  C1  D1  key1
2  A2  B2  C2  D2  key2
3  A3  B3  C3  D3  key3