In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import missingno as msno

#SERIES

In [4]:
exam1 = [86,84,92,98]

In [5]:
labels = ['Student A','Student B','Student C','Student D']

In [6]:
pd.Series(exam1,labels)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [7]:
pd.Series(exam1,labels)['Student D']

np.int64(98)

# Tworzymy słownik, gdzie:
# s = element z listy labels (klucz)
# p = odpowiadający element z listy exam1 (wartość)
# zip łączy obie listy w pary (s, p)

In [8]:
d = {s:p for s,p in zip(labels,exam1)} #funkcja zip łączy dwa zbiory w pary.

In [9]:
d

{'Student A': 86, 'Student B': 84, 'Student C': 92, 'Student D': 98}

In [10]:
pd.Series(d)

Student A    86
Student B    84
Student C    92
Student D    98
dtype: int64

In [11]:
exam2 = [74,56,44,92]

In [12]:
e1=pd.Series(exam1,labels)

In [13]:
e2=pd.Series(exam2,labels)

In [14]:
e1 + e2

Student A    160
Student B    140
Student C    136
Student D    190
dtype: int64

In [15]:
e1 * e2

Student A    6364
Student B    4704
Student C    4048
Student D    9016
dtype: int64

In [16]:
e1 - e2

Student A    12
Student B    28
Student C    48
Student D     6
dtype: int64

In [17]:
e1 / e2

Student A    1.162162
Student B    1.500000
Student C    2.090909
Student D    1.065217
dtype: float64

#DataFrame

In [18]:
df=pd.DataFrame({'e1':exam1, 'e2':exam2}, index=labels)

In [19]:
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [20]:
type(df['e1'])

pandas.Series

In [21]:
data = np.array([exam1,exam2])

In [22]:
data.transpose()

array([[86, 74],
       [84, 56],
       [92, 44],
       [98, 92]])

In [23]:
df = pd.DataFrame(data.transpose(),index=labels,columns=['e1','e2'])
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [24]:
df.to_numpy() #DataFrame możemy przekształcić w drugą stronę, to znaczy zamienić DataFrame na ndarray.

array([[86, 74],
       [84, 56],
       [92, 44],
       [98, 92]])

Series przechowuje dane jednego typu, jednak DataFrame to połączenie różnych Series. W związku z tym w DataFrame mogą pojawić się dane o różnym typie. We wcześniejszym module mogliśmy zobaczyć, że cała tablica ndarray posiada dane jednego typu. Jeśli masz DataFrame, dla których jedna Series to object, a pozostałe 99 Series to float, to taki DataFrame przekształcony w ndarray będzie posiadał wszystkie dane typu object.

In [25]:
df['e3'] = [67,59,79,84]

In [26]:
df

           e1  e2  e3
Student A  86  74  67
Student B  84  56  59
Student C  92  44  79
Student D  98  92  84

In [27]:
df ['semestr1'] = df['e1'] + df['e2'] + df['e3']

In [28]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

METODA LOC

In [29]:
df.loc['Student C']

e1           92
e2           44
e3           79
semestr1    215
Name: Student C, dtype: int64

In [30]:
df.loc['Student C','e2'] #indexing

np.int64(44)

In [31]:
df.loc[['Student C','Student D'],['e2']] #fancy indexing

           e2
Student C  44
Student D  92

METODA ILOC

In [32]:
df.iloc[1]

e1           84
e2           56
e3           59
semestr1    199
Name: Student B, dtype: int64

In [33]:
df.loc['Student C']

e1           92
e2           44
e3           79
semestr1    215
Name: Student C, dtype: int64

In [34]:
df.iloc[1:,1] #SLICING

Student B    56
Student C    44
Student D    92
Name: e2, dtype: int64

Masking na podstawie wyrażeń logicznych

In [35]:
df['e2'] > 70

Student A     True
Student B    False
Student C    False
Student D     True
Name: e2, dtype: bool

In [36]:
df[df['e2'] > 70]

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student D  98  92  84       274

In [37]:
df[(df['e2']<50)|(df['e2']>90)]

           e1  e2  e3  semestr1
Student C  92  44  79       215
Student D  98  92  84       274

In [38]:
df[(df['e2']<50)|(df['e3']>90)]

           e1  e2  e3  semestr1
Student C  92  44  79       215

#USUWANIE WIERSZY - DROP + inplace=True

In [39]:
df.drop('semestr1',axis=1)

           e1  e2  e3
Student A  86  74  67
Student B  84  56  59
Student C  92  44  79
Student D  98  92  84

In [40]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

Po wykonaniu tej operacji wywołajmy jeszcze raz zmienną df w komórce poniżej, a zauważmy, że kolumna w dalszym ciągu tam jest i ma się dobrze!Dzieje się tak, ponieważ wykonując funkcję drop, nie ustawiliśmy wartości True dla parametru Inplace. Parametr ten jest swego rodzaju zaworem bezpieczeństwa, który pozwala nam wykonać jakąś operację bez rzeczywistej ingerencji we wprowadzoną wcześniej tabelę. Musimy w tym miejscu powiedzieć, że wiele funkcji Pandas działa właśnie w ten sposób, a parametr Inplace będzie przewijał się w trakcie tego szkolenia również przy innych modyfikacjach DataFrame.

Usuńmy zatem kolumny z tabeli przypisanej do zmiennej df raz na zawsze. Jednak tym razem na potrzeby przykładu razem z kolumną semester1 usuńmy kolumnę e3. W tym celu, jako pierwszy argument funkcji drop musimy wprowadzić listę kolumn do usunięcia.

In [41]:
df

           e1  e2  e3  semestr1
Student A  86  74  67       227
Student B  84  56  59       199
Student C  92  44  79       215
Student D  98  92  84       274

In [42]:
df.drop(['e3','semestr1'],axis=1,inplace=True)

In [43]:
df

           e1  e2
Student A  86  74
Student B  84  56
Student C  92  44
Student D  98  92

In [44]:
df.drop('Student B',inplace=True)
df

           e1  e2
Student A  86  74
Student C  92  44
Student D  98  92

#RESETOWANIE INDEKSU

In [45]:
df.reset_index() # jeśli chcemy zachować zmiany, musimy użyć parametru inplace

       index  e1  e2
0  Student A  86  74
1  Student C  92  44
2  Student D  98  92

In [46]:
df

           e1  e2
Student A  86  74
Student C  92  44
Student D  98  92

In [47]:
df = df.reindex(['Student A', 'Student B', 'Student C', 'Student D'])  #dodanie brakującego studenta

In [48]:
df

             e1    e2
Student A  86.0  74.0
Student B   NaN   NaN
Student C  92.0  44.0
Student D  98.0  92.0

In [49]:
df['e3'] = [70, 85, 90, 88]

In [50]:
df

             e1    e2  e3
Student A  86.0  74.0  70
Student B   NaN   NaN  85
Student C  92.0  44.0  90
Student D  98.0  92.0  88

In [51]:
df.loc['Student B', 'e1'] = 82
df.loc['Student B', 'e2'] = 77

In [52]:
df

             e1    e2  e3
Student A  86.0  74.0  70
Student B  82.0  77.0  85
Student C  92.0  44.0  90
Student D  98.0  92.0  88

In [53]:
df ['semestr1'] = df['e1'] + df['e2'] + df['e3']

In [54]:
df

             e1    e2  e3  semestr1
Student A  86.0  74.0  70     230.0
Student B  82.0  77.0  85     244.0
Student C  92.0  44.0  90     226.0
Student D  98.0  92.0  88     278.0

#ZMIANA INDEXU

In [55]:
df_new_index = df.reset_index()
df_new_index

       index    e1    e2  e3  semestr1
0  Student A  86.0  74.0  70     230.0
1  Student B  82.0  77.0  85     244.0
2  Student C  92.0  44.0  90     226.0
3  Student D  98.0  92.0  88     278.0

In [56]:
df_new_index['student_name'] = ['Marek','Michal','Oskar','Kamil']

In [57]:
df_new_index

       index    e1    e2  e3  semestr1 student_name
0  Student A  86.0  74.0  70     230.0        Marek
1  Student B  82.0  77.0  85     244.0       Michal
2  Student C  92.0  44.0  90     226.0        Oskar
3  Student D  98.0  92.0  88     278.0        Kamil

In [58]:
df_new_index.set_index('student_name')

                  index    e1    e2  e3  semestr1
student_name
Marek         Student A  86.0  74.0  70     230.0
Michal        Student B  82.0  77.0  85     244.0
Oskar         Student C  92.0  44.0  90     226.0
Kamil         Student D  98.0  92.0  88     278.0

#drugi sposob na zmiane indexu

In [59]:
df_new_index2 = df.reset_index()

In [60]:
df_new_index

       index    e1    e2  e3  semestr1 student_name
0  Student A  86.0  74.0  70     230.0        Marek
1  Student B  82.0  77.0  85     244.0       Michal
2  Student C  92.0  44.0  90     226.0        Oskar
3  Student D  98.0  92.0  88     278.0        Kamil

In [61]:
df_new_index.drop(['student_name'],axis=1,inplace=True)

In [62]:
df_new_index

       index    e1    e2  e3  semestr1
0  Student A  86.0  74.0  70     230.0
1  Student B  82.0  77.0  85     244.0
2  Student C  92.0  44.0  90     226.0
3  Student D  98.0  92.0  88     278.0

In [63]:
df_new_index2.index = ['Marek','Michal','Oskar','Kamil']

In [64]:
df_new_index2

            index    e1    e2  e3  semestr1
Marek   Student A  86.0  74.0  70     230.0
Michal  Student B  82.0  77.0  85     244.0
Oskar   Student C  92.0  44.0  90     226.0
Kamil   Student D  98.0  92.0  88     278.0

#RENAME

In [65]:
df.rename(columns={'e1':'exam1','e2':'exam2','e3':'exam3'})

           exam1  exam2  exam3  semestr1
Student A   86.0   74.0     70     230.0
Student B   82.0   77.0     85     244.0
Student C   92.0   44.0     90     226.0
Student D   98.0   92.0     88     278.0

In [66]:
#rename z zastosawanie funkcji

In [67]:
df.rename(str.upper, axis='columns')

             E1    E2  E3  SEMESTR1
Student A  86.0  74.0  70     230.0
Student B  82.0  77.0  85     244.0
Student C  92.0  44.0  90     226.0
Student D  98.0  92.0  88     278.0

#Unique, value_counts, sort_values, drop_duplicates

In [68]:
df = pd.DataFrame({'A':[100,44,56,99,85,100],
                  'B':['Panda','Snake','Snake','Rat','Dog','Panda']})

In [69]:
df

     A      B
0  100  Panda
1   44  Snake
2   56  Snake
3   99    Rat
4   85    Dog
5  100  Panda

In [70]:
df['B'].unique()

<StringArray>
['Panda', 'Snake', 'Rat', 'Dog']
Length: 4, dtype: str

In [71]:
df['B'].nunique()

4

In [72]:
df['B'].value_counts()

B
Panda    2
Snake    2
Rat      1
Dog      1
Name: count, dtype: int64

In [73]:
df['B'].value_counts(normalize=True)   #% udział

B
Panda    0.333333
Snake    0.333333
Rat      0.166667
Dog      0.166667
Name: proportion, dtype: float64

In [74]:
df.sort_values(by='A')  #sortowanie

     A      B
1   44  Snake
2   56  Snake
4   85    Dog
3   99    Rat
0  100  Panda
5  100  Panda

In [75]:
df.sort_values(by='A',ascending=False)

     A      B
0  100  Panda
5  100  Panda
3   99    Rat
4   85    Dog
2   56  Snake
1   44  Snake

In [76]:
df.drop_duplicates() #usun_duplikaty

     A      B
0  100  Panda
1   44  Snake
2   56  Snake
3   99    Rat
4   85    Dog

M U L T I_I D E X

In [77]:
exam1 = [89,85,93,83]
exam2 = [74,56,44,92]
exam3=[67,59,79,84]
df = pd.DataFrame({'e1':exam1, 'e2':exam2, 'e3':exam3}, index=labels)
df['semester1'] = df['e1']+df['e2']+df['e3']

In [78]:
df

           e1  e2  e3  semester1
Student A  89  74  67        230
Student B  85  56  59        200
Student C  93  44  79        216
Student D  83  92  84        259

pierwszy sposob - MultiIndex.from_tuples

In [79]:
schools = ['High School X','High School X','High School Y','High School Y']
multi_index_list = [(school,student) for school,student in zip(schools,df.index)]
multi_index_list

[('High School X', 'Student A'),
 ('High School X', 'Student B'),
 ('High School Y', 'Student C'),
 ('High School Y', 'Student D')]

In [80]:
df.index = pd.MultiIndex.from_tuples(multi_index_list,names=['School','Student'])
df

                         e1  e2  e3  semester1
School        Student
High School X Student A  89  74  67        230
              Student B  85  56  59        200
High School Y Student C  93  44  79        216
              Student D  83  92  84        259

drugi sposob - funkcja set_index

In [81]:
df.set_index([pd.Index(['High School X','High School X','High School Y','High School Y']), df.index],inplace=True)

In [82]:
df

                                       e1  e2  e3  semester1
              School        Student
High School X High School X Student A  89  74  67        230
                            Student B  85  56  59        200
High School Y High School Y Student C  93  44  79        216
                            Student D  83  92  84        259

In [83]:
df.set_index.names = ['School','Student']
df

AttributeError: 'method' object has no attribute 'names' and no __dict__ for setting new attributes

In [ ]:
len(df)

In [ ]:
len(['High School X','High School X','High School Y','High School Y'])

In [ ]:
df.index.nlevels

In [ ]:
print(df.index.names)

In [ ]:
df = df.reset_index(drop=True)

df.index = pd.MultiIndex.from_arrays(
    [
        ['High School X','High School X','High School Y','High School Y'],
        df.index
    ],
    names=['School','Student']
)

In [ ]:
df

In [ ]:
df.loc['High School X']

In [ ]:
df = df.reset_index()

In [ ]:
df['Student'] = ['Student A','Student B','Student C','Student D']

In [ ]:
df = df.set_index(['School', 'Student', 'e1', 'e2', 'e3', 'semester1'])

In [ ]:
df

In [ ]:
df.loc['High School X']

In [ ]:
df.loc['High School X'].iloc[1]

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.loc['High School X']

In [ ]:
df.columns

In [ ]:
df = df.reset_index()

In [ ]:
df = df.set_index(['School','Student'])

In [ ]:
df

In [ ]:
df.index
df.index.names

In [ ]:
df.loc['High School X'].iloc[1]

In [ ]:
df.xs('High School Y')

In [ ]:
df.xs(('High School Y','Student D'))

In [ ]:
df.xs('Student D',level='Student')

Ćwiczenie
Do tabeli przypisanej do zmiennej df dodaj kolumny: e4, e5, e6. Niech wektory tych kolumn odzwierciedlają wyniki z kolejnych egzaminów w drugim semestrze Studentów A, B, C oraz D. Wyniki tych egzaminów niech będą losowane z liczb całkowitych o zakresie 1-100 włącznie. Następnie usuń kolumnę semester1. Po wykonaniu tych operacji stwórz indeks hierarchiczny dla kolumn tabeli, tak aby jego najwyższym rzędem było oznaczenie semestru, w którym napisany był dany egzamin.

In [ ]:
df['e4']=np.random.randint(1,101,size=len(df))

In [ ]:
df['e5']=np.random.randint(1,101,size=len(df))
df['e6']=np.random.randint(1,101,size=len(df))

In [ ]:
df

In [ ]:
df.drop(columns='semester1', inplace=True)   #usuniecie kolumny

In [ ]:
df

 Zbudowanie MultiIndex dla kolumn
(Semestr → Egzamin)

In [ ]:
cols = pd.MultiIndex.from_tuples(
    [
        ('Semestr 1','e1'),
        ('Semestr 1','e2'),
        ('Semestr 1','e3'),
        ('Semestr 2','e4'),
        ('Semestr 2','e5'),
        ('Semestr 2','e6'),
    ],
    names=['Semestr','Egzamin']
)

In [ ]:
df.columns = cols

In [ ]:
df

In [ ]:
df['Semestr 1']

In [ ]:
df['Semestr 2']['e5']

# GROUPBY

In [ ]:
df = pd.DataFrame({'Category':['Games','Games','Games',

                               'Film&Video','Film&Video','Film&Video'],

                  'Project_Title':['The Last Faith','Magic Puzzles','Dinosaur Fossil Hunter',

                                   'Beyond Your Eyes','5150','8-Bit Wars'],

                  'Pledged':[92774,2873519,7962,

                             276,23963,6950],

                  'Country':['UK','USA','Poland',

                             'Bulgaria','USA','UK'],

                  'Date_Start':['2020-03-21','2020-03-11','2020-04-16',

                                '2020-02-09','2020-04-10','2020-03-19']})

In [ ]:
df

In [ ]:
df.groupby('Category')

Jeśli wywołamy funkcję Groupby i wskażemy tylko kolumnę, według której chcemy wykonać grupowanie, otrzymamy z powrotem jedynie informację o miejscu w pamięci, gdzie możemy znaleźć obiekt Groupby. Jeśli chcemy otrzymać z powrotem pogrupowany DataFrame, musimy wykonać funkcję agregującą informacje w wierszac

In [ ]:
df.groupby('Category').sum()

In [ ]:
df.groupby('Category')['Pledged'].sum()

In [ ]:
df.groupby('Category')['Pledged'].mean()

In [ ]:
df.groupby('Category').count()

In [ ]:
df['Date_Start'] = pd.to_datetime(df['Date_Start'])

In [ ]:
df

In [ ]:
df.groupby(pd.Grouper(key='Date_Start',freq='ME')).sum()

Rozwijając problem, który rozwiązaliśmy w poprzednim przykładzie, spróbujemy teraz jednym poleceniem zgrupować projekty według miesiąca ‘Date_Start’, tak aby oprócz zebranej dotychczas sumy mieć obok informację o liczbie składających się na nią projektów.

W tym celu, zamiast podawać jedną funkcję agregującą, wykorzystamy agg, w której sprecyzujemy sposób agregowania każdej kolumny.

In [ ]:
df.groupby(pd.Grouper(key='Date_Start',freq='ME')).agg({'Pledged':'sum','Project_Title':'count'})

In [ ]:
df.groupby(['Country','Category',])['Pledged'].sum() #to zwraca series

In [ ]:
df.groupby(['Country','Category'], as_index=False)['Pledged'].sum() # a to DF

In [ ]:
df.groupby(['Country','Category']).agg({'Pledged':'sum'})

In [ ]:
df.index.names

In [ ]:
df.groupby('Country')['Pledged'].mean().sort_values(ascending=False).head(1)

In [ ]:
df.groupby('Category')['Project_Title'].count()

In [ ]:
df.groupby('Category')['Pledged'].sum().sort_values(ascending=False).head(1)

In [ ]:
df.loc[df.groupby('Country')['Pledged'].idxmax()]

# BRAKUJACE DANE

In [ ]:
df_with_nulls = pd.DataFrame({'A':[1,100,np.nan,1000,10000],
                             'B':[2,4,2,4,np.nan],
                             'C':[40,np.nan,20,np.nan,np.nan]})
df_with_nulls

In [ ]:
print(df_with_nulls.isnull().mean())
print()
print(df_with_nulls.isnull().sum())

In [ ]:
df_with_nulls[df_with_nulls['C'].isnull()]

#DROPNA

In [ ]:
msno.matrix(df_with_nulls)

In [ ]:
df_with_nulls

In [ ]:
df_with_nulls.dropna()

TRESH - minimalną liczbę uzupełnionych wartości w wierszu, która kwalifikuje go do pozostania w tabeli.

In [ ]:
df_with_nulls.dropna(thresh=2)

In [ ]:
df_with_nulls.dropna(thresh=3,axis=1) # mozna wyrzucac ten kolumny

In [ ]:
df_with_nulls.fillna('NOWA WARTOŚĆ')

In [ ]:
df_with_nulls['B'].fillna(df_with_nulls['B'].mean())  #uzupelnienie brakujacych wartosci na podstawie sredniej wartosci z danej kolumny

In [ ]:
df_with_nulls['A'].ffill()

In [ ]:
df_with_nulls['A'].bfill()

In [ ]:
# zeby zmienilo dane df_with_nulls['A'] = df_with_nulls['A'].bfill()

In [85]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],

                    'B': ['B0', 'B1', 'B2', 'B3'],

                    'C': ['C0', 'C1', 'C2', 'C3'],

                    'D': ['D0', 'D1', 'D2', 'D3']},

                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],

                    'B': ['B4', 'B5', 'B6', 'B7'],

                    'C': ['C4', 'C5', 'C6', 'C7'],

                    'D': ['D4', 'D5', 'D6', 'D7']},

                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],

                    'B': ['B8', 'B9', 'B10', 'B11'],

                    'C': ['C8', 'C9', 'C10', 'C11'],

                    'D': ['D8', 'D9', 'D10', 'D11']},

                    index=[8, 9, 10, 11])

In [93]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [86]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# CONCATENATE

In [87]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [94]:
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [88]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s])

     A    B    C    D    0
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
0  NaN  NaN  NaN  NaN   S1
1  NaN  NaN  NaN  NaN   S2
2  NaN  NaN  NaN  NaN   S3
3  NaN  NaN  NaN  NaN   S4

In [89]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s],axis=1)

    A   B   C   D   0
0  A0  B0  C0  D0  S1
1  A1  B1  C1  D1  S2
2  A2  B2  C2  D2  S3
3  A3  B3  C3  D3  S4

In [90]:
pd.concat([df1,df2,df3],axis=1,keys=['first','second','third'])

   first                second                third
       A    B    C    D      A    B    C    D     A    B    C    D
0     A0   B0   C0   D0    NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN
1     A1   B1   C1   D1    NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN
2     A2   B2   C2   D2    NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN
3     A3   B3   C3   D3    NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN
4    NaN  NaN  NaN  NaN     A4   B4   C4   D4   NaN  NaN  NaN  NaN
5    NaN  NaN  NaN  NaN     A5   B5   C5   D5   NaN  NaN  NaN  NaN
6    NaN  NaN  NaN  NaN     A6   B6   C6   D6   NaN  NaN  NaN  NaN
7    NaN  NaN  NaN  NaN     A7   B7   C7   D7   NaN  NaN  NaN  NaN
8    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN    A8   B8   C8   D8
9    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN    A9   B9   C9   D9
10   NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN   A10  B10  C10  D10
11   NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN   A11  B11  C11  D11

In [91]:
s = pd.Series(['S1','S2','S3','S4'])
pd.concat([df1,s])

     A    B    C    D    0
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
0  NaN  NaN  NaN  NaN   S1
1  NaN  NaN  NaN  NaN   S2
2  NaN  NaN  NaN  NaN   S3
3  NaN  NaN  NaN  NaN   S4

Ćwiczenie
Połącz ze sobą df1, df2, df3 wzdłuż osi poziomej używając funkcji concat. Postaraj się, aby połączona tabela nie rozszerzała się na dodatkowe wiersze w dół.

In [92]:


# reset indexów
df1_reset = df1.reset_index(drop=True)
df2_reset = df2.reset_index(drop=True)
df3_reset = df3.reset_index(drop=True)

# concat poziomy
result = pd.concat([df1_reset, df2_reset, df3_reset], axis=1)

print(result)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

-reset_index(drop=True) → ustawia index 0,1,2,3 dla wszystkich
-axis=1 → łączenie w poziomie (kolumny)
-dzięki temu pandas nie dodaje nowych wierszy